name: test_assessmentdata

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@master
      
      - name: Install command line packages
        run: |        
          sudo R CMD javareconf
          sudo apt-get install libcurl4-openssl-dev libgdal-dev libgit2-dev libudunits2-dev
        
      - name: Install assessmentdata
        run: |
          Rscript -e 'install.packages("remotes")
          remotes::install_github("NOAA-EDAB/assessmentdata")'
          
      - name: Test assessmentdata::stockAssessmentSummary nrows - 2004 when run locally
        run: |
          Rscript -e 'print(nrow(assessmentdata::stockAssessmentSummary))'
          
      - name: Test assessmentdata::stockAssessmentData nrows - 187655 when run locally
        run: |
          Rscript -e 'print(nrow(assessmentdata::stockAssessmentData))'
